### ISSUE TITLE
Crashed on onDraw method

### ISSUE THREAD

**Issue by fanbinzj** [yankai-victor/Loading#16]
Just got a crash log from google play console:

java.lang.NullPointerException: 
  at android.graphics.Canvas.drawArc(Canvas.java:1197)
  at com.victor.loading.rotate.RotateLoading.onDraw(RotateLoading.java:111)
  at android.view.View.draw(View.java:16201)
  at android.view.View.updateDisplayListIfDirty(View.java:15198)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.draw(View.java:16204)
  at android.view.View.updateDisplayListIfDirty(View.java:15198)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3424)
  at android.view.View.updateDisplayListIfDirty(View.java:15193)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.updateDisplayListIfDirty(View.java:15193)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1131)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.draw(View.java:16204)
  at android.view.View.updateDisplayListIfDirty(View.java:15198)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.draw(View.java:16204)
  at android.view.View.updateDisplayListIfDirty(View.java:15198)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.updateDisplayListIfDirty(View.java:15193)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.updateDisplayListIfDirty(View.java:15193)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.updateDisplayListIfDirty(View.java:15193)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.updateDisplayListIfDirty(View.java:15193)
  at android.view.View.draw(View.java:15971)
  at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
  at android.view.View.draw(View.java:16204)
  at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
  at android.view.View.updateDisplayListIfDirty(View.java:15198)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
  at android.view.Choreographer.doCallbacks(Choreographer.java:672)
  at android.view.Choreographer.doFrame(Choreographer.java:608)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5438)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

the version i am using is 1.0.4

Please advise me how to fix this or the what reason for this. Thanks.

**Comment by yankai-victor** [comment]
` canvas.drawArc(shadowRectF, topDegree, arc, false, mPaint);`
mPaint is not null, because it's used on line 110. I think it might be shadowRectF. But I'm not sure why shadowRectF is null.
