### ISSUE TITLE
Getting IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sktslf** [yankai-victor/Loading#21]
This is the stacktrace
 java.lang.IndexOutOfBoundsException: Index: 4, Size: 0
                                                                            at java.util.ArrayList.get(ArrayList.java:411)
                                                                            at com.victor.loading.book.BookLoading.playAnim(BookLoading.java:77)
                                                                            at com.victor.loading.book.BookLoading.access$000(BookLoading.java:24)
                                                                            at com.victor.loading.book.BookLoading$BookHandler.handleMessage(BookLoading.java:160)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:159)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6139)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

just using this
```
    private void progressWidget(Boolean start){
        if(start){
            bookLoading.start();
            layoutprogress.setVisibility(View.VISIBLE);
        }
        `else{`
            bookLoading.stop();
            layoutprogress.setVisibility(View.GONE);
        }
    }
```

**Comment by sktslf** [comment]
Fixed. It's was just missing View initialization.
